/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClustersRouteImport } from './routes/_app/clusters'
import { Route as AppStreamsIndexRouteImport } from './routes/_app/streams/index'
import { Route as AppObjectstoreIndexRouteImport } from './routes/_app/objectstore/index'
import { Route as AppKvIndexRouteImport } from './routes/_app/kv/index'
import { Route as AppConsumersIndexRouteImport } from './routes/_app/consumers/index'
import { Route as AppStreamsClusterIdNameRouteImport } from './routes/_app/streams/$clusterId/$name'
import { Route as AppObjectstoreClusterIdBucketRouteImport } from './routes/_app/objectstore/$clusterId/$bucket'
import { Route as AppKvClusterIdBucketRouteImport } from './routes/_app/kv/$clusterId/$bucket'
import { Route as AppConsumersClusterIdStreamConsumerRouteImport } from './routes/_app/consumers/$clusterId/$stream/$consumer'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClustersRoute = AppClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AppRoute,
} as any)
const AppStreamsIndexRoute = AppStreamsIndexRouteImport.update({
  id: '/streams/',
  path: '/streams/',
  getParentRoute: () => AppRoute,
} as any)
const AppObjectstoreIndexRoute = AppObjectstoreIndexRouteImport.update({
  id: '/objectstore/',
  path: '/objectstore/',
  getParentRoute: () => AppRoute,
} as any)
const AppKvIndexRoute = AppKvIndexRouteImport.update({
  id: '/kv/',
  path: '/kv/',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumersIndexRoute = AppConsumersIndexRouteImport.update({
  id: '/consumers/',
  path: '/consumers/',
  getParentRoute: () => AppRoute,
} as any)
const AppStreamsClusterIdNameRoute = AppStreamsClusterIdNameRouteImport.update({
  id: '/streams/$clusterId/$name',
  path: '/streams/$clusterId/$name',
  getParentRoute: () => AppRoute,
} as any)
const AppObjectstoreClusterIdBucketRoute =
  AppObjectstoreClusterIdBucketRouteImport.update({
    id: '/objectstore/$clusterId/$bucket',
    path: '/objectstore/$clusterId/$bucket',
    getParentRoute: () => AppRoute,
  } as any)
const AppKvClusterIdBucketRoute = AppKvClusterIdBucketRouteImport.update({
  id: '/kv/$clusterId/$bucket',
  path: '/kv/$clusterId/$bucket',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumersClusterIdStreamConsumerRoute =
  AppConsumersClusterIdStreamConsumerRouteImport.update({
    id: '/consumers/$clusterId/$stream/$consumer',
    path: '/consumers/$clusterId/$stream/$consumer',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/clusters': typeof AppClustersRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/consumers/': typeof AppConsumersIndexRoute
  '/kv/': typeof AppKvIndexRoute
  '/objectstore/': typeof AppObjectstoreIndexRoute
  '/streams/': typeof AppStreamsIndexRoute
  '/kv/$clusterId/$bucket': typeof AppKvClusterIdBucketRoute
  '/objectstore/$clusterId/$bucket': typeof AppObjectstoreClusterIdBucketRoute
  '/streams/$clusterId/$name': typeof AppStreamsClusterIdNameRoute
  '/consumers/$clusterId/$stream/$consumer': typeof AppConsumersClusterIdStreamConsumerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/clusters': typeof AppClustersRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/consumers': typeof AppConsumersIndexRoute
  '/kv': typeof AppKvIndexRoute
  '/objectstore': typeof AppObjectstoreIndexRoute
  '/streams': typeof AppStreamsIndexRoute
  '/kv/$clusterId/$bucket': typeof AppKvClusterIdBucketRoute
  '/objectstore/$clusterId/$bucket': typeof AppObjectstoreClusterIdBucketRoute
  '/streams/$clusterId/$name': typeof AppStreamsClusterIdNameRoute
  '/consumers/$clusterId/$stream/$consumer': typeof AppConsumersClusterIdStreamConsumerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/clusters': typeof AppClustersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/consumers/': typeof AppConsumersIndexRoute
  '/_app/kv/': typeof AppKvIndexRoute
  '/_app/objectstore/': typeof AppObjectstoreIndexRoute
  '/_app/streams/': typeof AppStreamsIndexRoute
  '/_app/kv/$clusterId/$bucket': typeof AppKvClusterIdBucketRoute
  '/_app/objectstore/$clusterId/$bucket': typeof AppObjectstoreClusterIdBucketRoute
  '/_app/streams/$clusterId/$name': typeof AppStreamsClusterIdNameRoute
  '/_app/consumers/$clusterId/$stream/$consumer': typeof AppConsumersClusterIdStreamConsumerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/clusters'
    | '/dashboard'
    | '/settings'
    | '/consumers/'
    | '/kv/'
    | '/objectstore/'
    | '/streams/'
    | '/kv/$clusterId/$bucket'
    | '/objectstore/$clusterId/$bucket'
    | '/streams/$clusterId/$name'
    | '/consumers/$clusterId/$stream/$consumer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/clusters'
    | '/dashboard'
    | '/settings'
    | '/consumers'
    | '/kv'
    | '/objectstore'
    | '/streams'
    | '/kv/$clusterId/$bucket'
    | '/objectstore/$clusterId/$bucket'
    | '/streams/$clusterId/$name'
    | '/consumers/$clusterId/$stream/$consumer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/clusters'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/consumers/'
    | '/_app/kv/'
    | '/_app/objectstore/'
    | '/_app/streams/'
    | '/_app/kv/$clusterId/$bucket'
    | '/_app/objectstore/$clusterId/$bucket'
    | '/_app/streams/$clusterId/$name'
    | '/_app/consumers/$clusterId/$stream/$consumer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clusters': {
      id: '/_app/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof AppClustersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/streams/': {
      id: '/_app/streams/'
      path: '/streams'
      fullPath: '/streams/'
      preLoaderRoute: typeof AppStreamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/objectstore/': {
      id: '/_app/objectstore/'
      path: '/objectstore'
      fullPath: '/objectstore/'
      preLoaderRoute: typeof AppObjectstoreIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kv/': {
      id: '/_app/kv/'
      path: '/kv'
      fullPath: '/kv/'
      preLoaderRoute: typeof AppKvIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumers/': {
      id: '/_app/consumers/'
      path: '/consumers'
      fullPath: '/consumers/'
      preLoaderRoute: typeof AppConsumersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/streams/$clusterId/$name': {
      id: '/_app/streams/$clusterId/$name'
      path: '/streams/$clusterId/$name'
      fullPath: '/streams/$clusterId/$name'
      preLoaderRoute: typeof AppStreamsClusterIdNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/objectstore/$clusterId/$bucket': {
      id: '/_app/objectstore/$clusterId/$bucket'
      path: '/objectstore/$clusterId/$bucket'
      fullPath: '/objectstore/$clusterId/$bucket'
      preLoaderRoute: typeof AppObjectstoreClusterIdBucketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kv/$clusterId/$bucket': {
      id: '/_app/kv/$clusterId/$bucket'
      path: '/kv/$clusterId/$bucket'
      fullPath: '/kv/$clusterId/$bucket'
      preLoaderRoute: typeof AppKvClusterIdBucketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumers/$clusterId/$stream/$consumer': {
      id: '/_app/consumers/$clusterId/$stream/$consumer'
      path: '/consumers/$clusterId/$stream/$consumer'
      fullPath: '/consumers/$clusterId/$stream/$consumer'
      preLoaderRoute: typeof AppConsumersClusterIdStreamConsumerRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClustersRoute: typeof AppClustersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppConsumersIndexRoute: typeof AppConsumersIndexRoute
  AppKvIndexRoute: typeof AppKvIndexRoute
  AppObjectstoreIndexRoute: typeof AppObjectstoreIndexRoute
  AppStreamsIndexRoute: typeof AppStreamsIndexRoute
  AppKvClusterIdBucketRoute: typeof AppKvClusterIdBucketRoute
  AppObjectstoreClusterIdBucketRoute: typeof AppObjectstoreClusterIdBucketRoute
  AppStreamsClusterIdNameRoute: typeof AppStreamsClusterIdNameRoute
  AppConsumersClusterIdStreamConsumerRoute: typeof AppConsumersClusterIdStreamConsumerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClustersRoute: AppClustersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppConsumersIndexRoute: AppConsumersIndexRoute,
  AppKvIndexRoute: AppKvIndexRoute,
  AppObjectstoreIndexRoute: AppObjectstoreIndexRoute,
  AppStreamsIndexRoute: AppStreamsIndexRoute,
  AppKvClusterIdBucketRoute: AppKvClusterIdBucketRoute,
  AppObjectstoreClusterIdBucketRoute: AppObjectstoreClusterIdBucketRoute,
  AppStreamsClusterIdNameRoute: AppStreamsClusterIdNameRoute,
  AppConsumersClusterIdStreamConsumerRoute:
    AppConsumersClusterIdStreamConsumerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
