/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConsumersRouteImport } from './routes/_app/consumers'
import { Route as AppClustersRouteImport } from './routes/_app/clusters'
import { Route as AppStreamsIndexRouteImport } from './routes/_app/streams/index'
import { Route as AppKvIndexRouteImport } from './routes/_app/kv/index'
import { Route as AppStreamsClusterIdNameRouteImport } from './routes/_app/streams/$clusterId/$name'
import { Route as AppKvClusterIdBucketRouteImport } from './routes/_app/kv/$clusterId/$bucket'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumersRoute = AppConsumersRouteImport.update({
  id: '/consumers',
  path: '/consumers',
  getParentRoute: () => AppRoute,
} as any)
const AppClustersRoute = AppClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AppRoute,
} as any)
const AppStreamsIndexRoute = AppStreamsIndexRouteImport.update({
  id: '/streams/',
  path: '/streams/',
  getParentRoute: () => AppRoute,
} as any)
const AppKvIndexRoute = AppKvIndexRouteImport.update({
  id: '/kv/',
  path: '/kv/',
  getParentRoute: () => AppRoute,
} as any)
const AppStreamsClusterIdNameRoute = AppStreamsClusterIdNameRouteImport.update({
  id: '/streams/$clusterId/$name',
  path: '/streams/$clusterId/$name',
  getParentRoute: () => AppRoute,
} as any)
const AppKvClusterIdBucketRoute = AppKvClusterIdBucketRouteImport.update({
  id: '/kv/$clusterId/$bucket',
  path: '/kv/$clusterId/$bucket',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/clusters': typeof AppClustersRoute
  '/consumers': typeof AppConsumersRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/kv/': typeof AppKvIndexRoute
  '/streams/': typeof AppStreamsIndexRoute
  '/kv/$clusterId/$bucket': typeof AppKvClusterIdBucketRoute
  '/streams/$clusterId/$name': typeof AppStreamsClusterIdNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/clusters': typeof AppClustersRoute
  '/consumers': typeof AppConsumersRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/kv': typeof AppKvIndexRoute
  '/streams': typeof AppStreamsIndexRoute
  '/kv/$clusterId/$bucket': typeof AppKvClusterIdBucketRoute
  '/streams/$clusterId/$name': typeof AppStreamsClusterIdNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/clusters': typeof AppClustersRoute
  '/_app/consumers': typeof AppConsumersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/kv/': typeof AppKvIndexRoute
  '/_app/streams/': typeof AppStreamsIndexRoute
  '/_app/kv/$clusterId/$bucket': typeof AppKvClusterIdBucketRoute
  '/_app/streams/$clusterId/$name': typeof AppStreamsClusterIdNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/clusters'
    | '/consumers'
    | '/dashboard'
    | '/settings'
    | '/kv/'
    | '/streams/'
    | '/kv/$clusterId/$bucket'
    | '/streams/$clusterId/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/clusters'
    | '/consumers'
    | '/dashboard'
    | '/settings'
    | '/kv'
    | '/streams'
    | '/kv/$clusterId/$bucket'
    | '/streams/$clusterId/$name'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/clusters'
    | '/_app/consumers'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/kv/'
    | '/_app/streams/'
    | '/_app/kv/$clusterId/$bucket'
    | '/_app/streams/$clusterId/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumers': {
      id: '/_app/consumers'
      path: '/consumers'
      fullPath: '/consumers'
      preLoaderRoute: typeof AppConsumersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clusters': {
      id: '/_app/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof AppClustersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/streams/': {
      id: '/_app/streams/'
      path: '/streams'
      fullPath: '/streams/'
      preLoaderRoute: typeof AppStreamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kv/': {
      id: '/_app/kv/'
      path: '/kv'
      fullPath: '/kv/'
      preLoaderRoute: typeof AppKvIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/streams/$clusterId/$name': {
      id: '/_app/streams/$clusterId/$name'
      path: '/streams/$clusterId/$name'
      fullPath: '/streams/$clusterId/$name'
      preLoaderRoute: typeof AppStreamsClusterIdNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kv/$clusterId/$bucket': {
      id: '/_app/kv/$clusterId/$bucket'
      path: '/kv/$clusterId/$bucket'
      fullPath: '/kv/$clusterId/$bucket'
      preLoaderRoute: typeof AppKvClusterIdBucketRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClustersRoute: typeof AppClustersRoute
  AppConsumersRoute: typeof AppConsumersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppKvIndexRoute: typeof AppKvIndexRoute
  AppStreamsIndexRoute: typeof AppStreamsIndexRoute
  AppKvClusterIdBucketRoute: typeof AppKvClusterIdBucketRoute
  AppStreamsClusterIdNameRoute: typeof AppStreamsClusterIdNameRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClustersRoute: AppClustersRoute,
  AppConsumersRoute: AppConsumersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppKvIndexRoute: AppKvIndexRoute,
  AppStreamsIndexRoute: AppStreamsIndexRoute,
  AppKvClusterIdBucketRoute: AppKvClusterIdBucketRoute,
  AppStreamsClusterIdNameRoute: AppStreamsClusterIdNameRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
